name: go-chi-ci
on:
  push:
    tags:
      - "v*-go-chi"
    paths:
      - "go/go-chi/**"
  workflow_dispatch:

jobs:
  go-mod-lint-test:
    uses: ./.github/workflows/template-golang.yaml
    with:
      work-dir: "go/go-chi"

  goreleaser:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - go-mod-lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go/go-chi/go.mod
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
          workdir: "go/go-chi"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
