name: go-chi-ci

on:
  push:
    paths:
      - "golang/go-chi/**"
  workflow_dispatch:

jobs:
  go-mod-lint-test:
    uses: ./.github/workflows/template-golang.yaml
    with:
      work-dir: "golang/go-chi"

  goreleaser:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/template-goreleaser.yaml
    permissions:
      contents: write
    with:
      work-dir: "golang/go-chi"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
