name: main-to-prod-pr-creator

on:
#  schedule:
#    - cron: '0 1 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-main-to-prod-pr:
    if: ${{ github.event.pull_request.base.ref == 'prod' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - uses: linzhengen/release-pr-creator@v0.1.3
